### PR TITLE
Group by carrier id reference

### LINKED ISSUE #28840: BO - Stats - Stats carrier is duplicated when a carrier is edited
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md)
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add screenshots

When you have a carrier used in orders , and you edit something of this carrier, the carrier is the same, but the stats separate this.
https://gyazo.com/a986b16b7fe4ff84985ca642be7bd31b

### Expected behavior

The carrier must be the same, because the id_carrier change, but not the id_reference.
https://gyazo.com/01b9e2946413c4f6407beb8df3e1dd67

### Steps to reproduce

1. Create a carrier
2. Create an order with this carrier.
3. Edit this carrier (prices or something)
4. Go to stats by carrier and check that there are 2 carriers with same name

### PrestaShop version(s) where the bug happened

1.7.6.8 (but happends in all)

### PHP version(s) where the bug happened

_No response_

### If your bug is related to a module, specify its name and its version

statscarrier

### PR DESCRIPTION
**Pull request by borjagarciab**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | If you group by id carrier, and later update the carrier (for example the prices) you will have the same carrier multiple times because is group by id carrier, not by carrier reference.
| Type?         | bug fix 
| BC breaks?    | no
| Deprecations? |no
| Fixed ticket? |  Fixes https://github.com/PrestaShop/PrestaShop/issues/28840
| How to test?  | Load the carrier stats

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
thank you @borjagarciab for your pull request 👍 

can you add an issue, with a description of steps to reproduce the issue, so that the product and QA team can properly follow the subject ?

**Comment by borjagarciab** [comment]
Hi,
Here is the ticket
https://github.com/PrestaShop/PrestaShop/issues/28840

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Thank you @borjagarciab can you edit the description of the PR to link your PR to the issue.

`Fixes PrestaShop/Prestashop#{issue number here}.`

**Comment by borjagarciab** [comment]
Updated :)

**Review by kpodemski — DISMISSED** [review]

**Comment by ghost** [comment]
Oh my bad you dont target the good branch.

**Review by ghost — CHANGES_REQUESTED** [review]
Plz target dev branch

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Hello @borjagarciab i am sorry again but you need to rebase for the conflict file.

Your PR is approve but we cant merge it if you need help tell us.

**Review by ghost — CHANGES_REQUESTED** [review]
Need rebase

**Comment by borjagarciab** [comment]
My bad sorry :(

Guess now is okey.
Thanks.

**Review by ghost — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @borjagarciab ,

Thanks for the PR !

Tested on develop, 8.0.x and 1.7.8.x, with statscarrier v2.0.1.

Issue is fixed.
Screenshot 2022-07-11 at 11 23 41
Screenshot 2022-07-11 at 11 31 00


Created multiples orders with different carriers.
Edited carriers from existing orders.
No carriers are duplicated.
Looking good to me ^^

It is QA ✅

**Comment by jolelievre** [comment]
Thanks @borjagarciab and @florine2623

**Pull request merged**
